name: Kotlin CI
on: [push]
jobs:
  build1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - id: set-matrix
        run: echo "matrix={\"app\":[\"Job 1\",\"Job 2\",\"Job 3\",\"Job 4\",\"Job 5\"]}" >> $GITHUB_OUTPUT

  build2:
    needs: build1
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix: ${{ fromJSON(needs.build1.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 11

      - name: Compile and run Kotlin file
        run: |
          status="${{ matrix.app }}"
          echo "Job ${{ matrix.app }} status: $status"
          kotlinc src/main/kotlin/Main.kt -include-runtime -d Main.jar
          java -jar Main.jar

  build3:
    needs: build2
    runs-on: ubuntu-latest
    steps:
      - name: Print build results
        run: |
          jobs=($(echo "$MATRIX" | jq -r '.app[]'))
          num_jobs=${#jobs[@]}
          echo "Total jobs run: $num_jobs"