name: Kotlin CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        app:
          - 1
          - 2
          - 3
          - 4
          - 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 11

      - name: Compile and run Kotlin file
        run: |
          echo "${{jobs.build.status}}"
          kotlinc src/main/kotlin/Main.kt -include-runtime -d Main.jar
          java -jar Main.jar

#  print_results:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Print build results
#        run: |
#          for job in "${{jobs.build}}"; do
#            status=${job.status}
#            echo "Job $job Status: $status"
#          done