name: Kotlin CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: ${{ fromJson(steps.setup_apps.outputs.app_matrix) }}


    steps:
      - name: Setup app matrix
        id: setup_apps
        run: |
          apps=$(cat count.txt)
          app_matrix=$(echo "$apps" | sed 's/.*/\1\n&/;s/^/\n/;s/$/\n/')
          echo "::set-output name=app_matrix::$(echo "$app_matrix" | jq -R -s 'split("\n")[:-1]')"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 11

      - name: Compile and run Kotlin file
        run: |
          kotlinc src/main/kotlin/Main.kt -include-runtime -d Main.jar
          java -jar Main.jar
