name: Kotlin CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        app:
          1: { name: "Job 1" }
          2: { name: "Job 2" }
          3: { name: "Job 3" }
          4: { name: "Job 4" }
          5: { name: "Job 5" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 11

      - name: Compile and run Kotlin file
        run: |
          status="${{ github.job.result }}"
          echo "Job ${{ matrix.app }} status: $status"
          kotlinc src/main/kotlin/Main.kt -include-runtime -d Main.jar
          java -jar Main.jar

  print_results:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print build results
        run: |
          echo "Total jobs run: ${{ strategy.job-total }}"