name: Kotlin CI

on: [push]

jobs:
  build1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Demo
        run: echo hi

    env:
      MY_VARIABLE: 42

  build2:
    needs: build1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Demo
        run: echo $MY_VARIABLE

  build3:
    needs: build2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Demo
        run: echo $MY_VARIABLE
