name: Kotlin CI
on: [push]
jobs:
  build1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - id: set-matrix
        run: echo "matrix={\"app\":[\"Job 1\",\"Job 2\",\"Job 3\",\"Job 4\",\"Job 5\"]}" >> $GITHUB_OUTPUT

  build2:
    needs: build1
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix: ${{ fromJSON(needs.build1.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 11

      - name: Compile and run Kotlin file
        run: |
          kotlinc src/main/kotlin/Main.kt -include-runtime -d Main.jar
          java -jar Main.jar
          continue-on-error: true
          if [ $? -eq 0 ]; then
            echo "completed" >> $GITHUB_OUTPUT
          else
            echo "failed" >> $GITHUB_OUTPUT
          fi

  build3:
    needs: build2
    runs-on: ubuntu-latest
    steps:
      - name: Count successes and failures
        run: |
          success=$(grep -o 'completed' $GITHUB_OUTPUT | wc -l)
          failure=$(grep -o 'failed' $GITHUB_OUTPUT | wc -l)
          echo "Total successful jobs: $success"
          echo "Total failed jobs: $failure"